### ISSUE TITLE
BUG: eps_writer.multiplot_yt regression in yt 4.1

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4215]
### Bug report

**Bug summary**

This bug was reported on Slack by @mihirskulkarni, I've  started minimizing the reproducer script

**Code for reproduction**

```python
import yt
import yt.visualization.eps_writer as eps
from yt.testing import fake_amr_ds

ds = fake_amr_ds(
    fields=[("gas", "density"), ("gas", "temperature")],
    units=["g/cm**3", "K"]
)

slc = yt.SlicePlot(
    ds,
    "y",
    [
        ("gas", "density"),
        ("gas", "temperature"),
    ],
)
eps_fig = eps.multiplot_yt(2, 1, slc)
```

**Actual outcome**

```
...
AttributeError: 'WindowPlotMPL' object has no attribute 'zmin'
```

This script worked on yt 4.0.5 and is broken since yt 4.1.0
The exact commit that this regression happened is 379c0826cb1ede4819995f2162d55e8d96cc6eea... This is an oversight from https://github.com/yt-project/yt/pull/3849

I'll work on a patch

**Comment by neutrinoceros** [comment]
Actually it seems that the one test in `yt/visualization/tests/test_eps_writer.py` is broken too, so my guess is that it is currently not run on any CI.
