### PR TITLE
fix a bug where set_background_color wouldn't work with colormaps from third party libs

### LINKED ISSUE #3208: set_background_color no longer works for cmocean colormaps
### Bug report

**Bug summary**

Something about the changes in PR #3175 seems to have broken `set_background_color` when using cmocean colormaps.  

**Code for reproduction**

This script used to work:

```
import yt

ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", 'Density')
p.set_cmap('all', "balance")
p.set_background_color('Density')
```

After applying the changes described in PR #3175 and now documented in PR #3207, this script show now look like this:

```
import yt
import cmocean

ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", 'Density')
p.set_cmap('all', "cmo.balance")
p.set_background_color('Density')
```

But it fails with this error:

```
Traceback (most recent call last):
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 896, in set_background_color
    cmap = yt_colormaps[cmap]
KeyError: 'cmo.balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cmo_test.py", line 7, in <module>
    p.set_background_color('Density')
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 105, in newfunc
    func(self, f, *args, **kwargs)
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 56, in newfunc
    rv = f(*args, **kwargs)
  File "/Users/chummels/src/yt/yt/visualization/plot_container.py", line 898, in set_background_color
    cmap = getattr(matplotlib.cm, cmap)
AttributeError: module 'matplotlib.cm' has no attribute 'cmo.balance'
```

### PR DESCRIPTION
**Pull request by neutrinoceros**
## PR Summary

fix #3208

edit: looks like my solution doesn't work across all versions of matplotlib.
For reference, I wrote it for ppl 3.3, now trying to generalise it.
edit 2: it also work with matplotlib 3.4
edit 3: should work for all currently supported versions of matplotlib now 🎉  (thanks to @cphyc  for his help in testing locally with "old" versions)

### CODE REVIEW

File: yt/visualization/plot_container.py [hunk 1]
```diff
@@ -892,10 +893,11 @@ def set_background_color(self, field, color=None):
...
             if isinstance(cmap, str):
-                try:
-                    cmap = yt_colormaps[cmap]
-                except KeyError:
-                    cmap = getattr(matplotlib.cm, cmap)
+                cmap = (
+                    yt_colormaps[cmap]
+                    if cmap in yt_colormaps
+                    else mpl_cmap_registry[cmap]
+                )
```
Comment (neutrinoceros) [inline yt/visualization/plot_container.py:900]: while this should be equivalent to the previous version, it should be noted that

```python
cmap = mpl_cmap_registry[cmap]
```
does the same thing

**Review by chummels — APPROVED** [review]
This addresses the problems I identified in Issue #3208.  Thanks for fixing this up, @neutrinoceros !
