### ISSUE TITLE
yt update --all fails when updating from numpy 1.7 to 1.8 on some systems

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#889]
Originally reported by: **chummels (Bitbucket: [chummels](https://bitbucket.org/chummels), GitHub: [chummels](https://github.com/chummels))**

----------------------------------------

Since the addition of Pull Request #1168, which updates the version of numpy from 1.7 to 1.8, some attempts to update yt's dependencies in place fail with this error:

```
#!python

ImportError: cannot import name multiarray
```

See here for full traceback: http://paste.yt-project.org/show/5077/

This appears to be a problem on mac systems and TACC Stampede, and perhaps others.

One solution to this is to wipe yt and reinstall from the install script, but a different solution is desired.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/889
