### ISSUE TITLE
REG: fail to configure yt from the command line if $HOME/.config/ doesn't exist

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4015]
### Bug report

**Bug summary**

This was discovered downstream thanks to yt_astro_analysis' CI

**Code for reproduction**
```shell
yt config set --global yt suppress_stream_logging True
```

**Actual outcome**

```python-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/configure.py", line 106, in write
    file_handler.write(config_as_str)
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robcleme/.pyenv/versions/38-yt-dev/bin/yt", line 33, in <module>
    sys.exit(load_entry_point('yt', 'console_scripts', 'yt')())
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/command_line.py", line 1632, in run_main
    args.func(args)
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/command_line.py", line 224, in run
    self(args)
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/command_line.py", line 1418, in __call__
    set_config(args.section, args.option, args.value, self.config_file)
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/configure.py", line 173, in set_config
    write_config(config_file)
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/configure.py", line 177, in write_config
    CONFIG.write(config_file)
  File "/Users/robcleme/dev/yt-project/yt/yt/utilities/configure.py", line 109, in write
    with open(file_handler, mode="w") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/robcleme/.config/yt/yt.toml'
```

**Expected outcome**

The configuration dir should be created.
I bet this regression is caused by #3626
