### ISSUE TITLE
plot collection add_projection not working?

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#585]
Originally reported by: **Kyle Stewart (Bitbucket: [kstewart](https://bitbucket.org/kstewart), GitHub: [kstewart](https://github.com/kstewart))**

----------------------------------------

When I try to run a very basic projection plot with yt 3.0 I get the following error:

pc=PlotCollection(pf, center)
pc.add_projection("Density", 'x', "Density")

/Users/kstewart/code/yt-3.0/yt-x86_64/src/yt-3.0-hg/yt/visualization/plot_collection.py in add_projection(self, field, axis, weight_field, data_source, center, use_colorbar, figure, axes, fig_size, periodic, obj, field_parameters)
    781             obj = self.pf.hierarchy.proj(field, axis, weight_field,
    782                                          source = data_source, center=center,
--> 783                                          **field_parameters)
    784         p = self._add_plot(PCProjectionPlot(obj, field,
    785                          use_colorbar=use_colorbar, axes=axes, figure=figure,

TypeError: __init__() got an unexpected keyword argument 'source'

Not sure what's going on here.  Looks like some kind of bug since this same code works perfectly in 2.5
-Kyle Stewart

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/585
