### ISSUE TITLE
mypy failure with np 2.2.4

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#5136]
Running mypy with the latest numpy (v 2.2.4, released 3 days ago) results in a new failure: 

```python
yt/__init__.py:98: note: In module imported here:
yt/testing.py: note: In function "integrate_kernel":
yt/testing.py:148: error: Argument 1 has incompatible type "ndarray[tuple[int, ...], dtype[Any]]"; expected "float"  [arg-type]
yt/utilities/performance_counters.py: note: In member "print_stats" of class "PerformanceCounters":
yt/utilities/performance_counters.py:73: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 1 error in 1 file (checked 516 source files)
```

**Comment by chrishavlin** [comment]
test failure seen in #5135
